/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Men' : null } |
  { 'Shawls' : null } |
  { 'Women' : null };
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : Category,
  'image' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], Product>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByPrice' : ActorMethod<[], Array<Product>>,
  'removeProductsEmptyEntries' : ActorMethod<[], undefined>,
  'saveContactInfo' : ActorMethod<[string, string, string], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];