/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Men' : IDL.Null,
  'Shawls' : IDL.Null,
  'Women' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [Product], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeProductsEmptyEntries' : IDL.Func([], [], []),
  'saveContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Men' : IDL.Null,
    'Shawls' : IDL.Null,
    'Women' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [Product], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeProductsEmptyEntries' : IDL.Func([], [], []),
    'saveContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };